hangman_client: hangman_client.c
	gcc -Wall -o hangman_client hangman_client.c
hangman_server: hangman_server.c
	gcc -Wall -o hangman_server hangman_server.c

clean:
	rm -f *.o hangman_client *~
	rm -f *.o hangman_server *~